version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - 5432

  redis:
    image: redis
    ports:
      - 6379

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 5672
      - 15672

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

