db:
  type: postgresql:latest
  disk: 1024
  size: S

rediscache:
  type: redis:latest

queue:
  type: rabbitmq:3.7
  disk: 1024
  size: S

varnish:
  type: varnish:latest
  relationships:
    application: 'app.http'
  configuration:
    vcl: !include
      type: string
      path: config.vcl
